// Mocks generated by Mockito 5.4.6 from annotations
// in funlearn_client/test/apkgImport_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:funlearn_client/data/apkgImport/ankiDbReader.dart' as _i5;
import 'package:funlearn_client/data/apkgImport/ankiDbWriter.dart' as _i8;
import 'package:funlearn_client/data/apkgImport/apkgExtractor.dart' as _i9;
import 'package:funlearn_client/data/apkgImport/apkgSource.dart' as _i3;
import 'package:funlearn_client/data/databaseHelper.dart' as _i2;
import 'package:funlearn_client/data/models/card.dart' as _i7;
import 'package:funlearn_client/data/models/deck.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApkgSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockApkgSource extends _i1.Mock implements _i3.ApkgSource {
  MockApkgSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> getApkgPath() =>
      (super.noSuchMethod(
            Invocation.method(#getApkgPath, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [AnkiDbReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnkiDbReader extends _i1.Mock implements _i5.AnkiDbReader {
  MockAnkiDbReader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<(List<_i6.Deck>, List<_i7.Card>)> read(String? folderPath) =>
      (super.noSuchMethod(
            Invocation.method(#read, [folderPath]),
            returnValue: _i4.Future<(List<_i6.Deck>, List<_i7.Card>)>.value((
              <_i6.Deck>[],
              <_i7.Card>[],
            )),
          )
          as _i4.Future<(List<_i6.Deck>, List<_i7.Card>)>);
}

/// A class which mocks [AnkiDbWriter].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnkiDbWriter extends _i1.Mock implements _i8.AnkiDbWriter {
  MockAnkiDbWriter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get helper =>
      (super.noSuchMethod(
            Invocation.getter(#helper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#helper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i4.Future<void> save((List<_i6.Deck>, List<_i7.Card>)? tuple) =>
      (super.noSuchMethod(
            Invocation.method(#save, [tuple]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ApkgExtractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockApkgExtractor extends _i1.Mock implements _i9.ApkgExtractor {
  MockApkgExtractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> extract(String? apkgPath) =>
      (super.noSuchMethod(
            Invocation.method(#extract, [apkgPath]),
            returnValue: _i4.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#extract, [apkgPath]),
              ),
            ),
          )
          as _i4.Future<String>);
}
